version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: uninus-grpc-boilerplate-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: uninusdb
    ports:
      - "5436:5432"
