// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListUserRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserRequest) Reset()         { *m = GetListUserRequest{} }
func (m *GetListUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetListUserRequest) ProtoMessage()    {}
func (*GetListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserRequest.Unmarshal(m, b)
}
func (m *GetListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserRequest.Marshal(b, m, deterministic)
}
func (m *GetListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserRequest.Merge(m, src)
}
func (m *GetListUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetListUserRequest.Size(m)
}
func (m *GetListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserRequest proto.InternalMessageInfo

func (m *GetListUserRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetListUserRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetListUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*User  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserResponse) Reset()         { *m = GetListUserResponse{} }
func (m *GetListUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetListUserResponse) ProtoMessage()    {}
func (*GetListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserResponse.Unmarshal(m, b)
}
func (m *GetListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserResponse.Marshal(b, m, deterministic)
}
func (m *GetListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserResponse.Merge(m, src)
}
func (m *GetListUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetListUserResponse.Size(m)
}
func (m *GetListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserResponse proto.InternalMessageInfo

func (m *GetListUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetListUserResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetListUserResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetListUserRequest)(nil), "grpc.GetListUserRequest")
	proto.RegisterType((*GetListUserResponse)(nil), "grpc.GetListUserResponse")
	proto.RegisterType((*User)(nil), "grpc.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0xed, 0xb6, 0x75, 0xa7, 0xe0, 0x61, 0xf4, 0x10, 0x0b, 0x4a, 0xd9, 0x53, 0x4f,
	0x2b, 0xd4, 0xa3, 0x20, 0x54, 0x04, 0x2f, 0x9e, 0x52, 0xbc, 0x78, 0x91, 0xd8, 0x0c, 0x25, 0xd0,
	0xed, 0xc6, 0x64, 0x56, 0x7f, 0x9b, 0xff, 0x4e, 0x92, 0xec, 0x8a, 0xa2, 0xb7, 0xbc, 0xf7, 0x25,
	0x2f, 0x8f, 0x19, 0x80, 0xce, 0x93, 0xab, 0xad, 0x6b, 0xb9, 0xc5, 0x62, 0xe7, 0xec, 0xb6, 0xba,
	0x05, 0x7c, 0x20, 0x7e, 0x34, 0x9e, 0x9f, 0x3c, 0x39, 0x49, 0x6f, 0x1d, 0x79, 0x46, 0x84, 0xc2,
	0xaa, 0x1d, 0x89, 0x6c, 0x91, 0x2d, 0xc7, 0x32, 0x9e, 0xf1, 0x0c, 0xc6, 0x7b, 0xd3, 0x18, 0x16,
	0x79, 0x34, 0x93, 0xa8, 0x08, 0x4e, 0x7f, 0xbd, 0xf7, 0xb6, 0x3d, 0x78, 0x42, 0x01, 0xd3, 0x86,
	0xbc, 0x1f, 0x32, 0x4a, 0x39, 0x48, 0xbc, 0x84, 0x42, 0x2b, 0x56, 0x22, 0x5f, 0x8c, 0x96, 0xb3,
	0x15, 0xd4, 0xa1, 0x45, 0x1d, 0xdf, 0x46, 0x3f, 0x7c, 0xc3, 0x2d, 0xab, 0xbd, 0x18, 0x2d, 0xb2,
	0xe5, 0x48, 0x26, 0x51, 0x7d, 0x66, 0x50, 0x84, 0x4b, 0x78, 0x02, 0xb9, 0xd1, 0x7d, 0x66, 0x6e,
	0x74, 0x68, 0x7a, 0x50, 0x0d, 0xc5, 0x52, 0xa5, 0x8c, 0xe7, 0x10, 0x41, 0x8d, 0x32, 0x29, 0xa2,
	0x94, 0x49, 0xe0, 0x1c, 0x8e, 0xad, 0xf2, 0xfe, 0xa3, 0x75, 0x5a, 0x14, 0x11, 0x7c, 0x6b, 0xbc,
	0x00, 0xd8, 0x3a, 0x52, 0x4c, 0xfa, 0x45, 0xb1, 0x18, 0x47, 0x5a, 0xf6, 0xce, 0x9a, 0x03, 0xee,
	0xac, 0x1e, 0xf0, 0x24, 0xe1, 0xde, 0x49, 0x58, 0xd3, 0x9e, 0x7a, 0x3c, 0x4d, 0xb8, 0x77, 0xd6,
	0xbc, 0xda, 0xc0, 0x2c, 0x54, 0xdf, 0x90, 0x7b, 0x37, 0x5b, 0xc2, 0x7b, 0x98, 0xfd, 0x98, 0x18,
	0x8a, 0x34, 0x81, 0xbf, 0x4b, 0x98, 0x9f, 0xff, 0x43, 0xd2, 0x78, 0xab, 0xa3, 0xbb, 0xf2, 0x79,
	0x5a, 0x5f, 0xdd, 0x84, 0x0b, 0xaf, 0x93, 0xb8, 0xcf, 0xeb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1a, 0xef, 0xaf, 0xcc, 0xdd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetListUser(ctx context.Context, in *GetListUserRequest, opts ...grpc.CallOption) (*GetListUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetListUser(ctx context.Context, in *GetListUserRequest, opts ...grpc.CallOption) (*GetListUserResponse, error) {
	out := new(GetListUserResponse)
	err := c.cc.Invoke(ctx, "/grpc.UserService/GetListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetListUser(context.Context, *GetListUserRequest) (*GetListUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetListUser(ctx context.Context, req *GetListUserRequest) (*GetListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/GetListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetListUser(ctx, req.(*GetListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListUser",
			Handler:    _UserService_GetListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
